### ISSUE TITLE
Add JavaScript-based search

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/formulae.brew.sh#12]
> [https://yarnpkg.com/en/](Yarn) is a package manager for node that uses [Algolia](https://www.algolia.com/) for search. I think it would be great to replicate that experience for homebrew users. Go ahead and try out the search to see what I'm talking about. You just type and results against all of the packages on npm are delivered instantly with no noticeable lag.
> 
> [Algolia is free for open source](https://www.algolia.com/for-open-source), for what it's worth.

This may require a different approach now this is using Jekyll/GitHub Pages.

(Imported from https://github.com/Homebrew/formulae.brew.sh/issues/23 CC @knpwrs @iam4x @pixelastic)

**Comment by MikeMcQuaid** [comment]
@knpwrs Cool, thanks. The JSON API provided by the new site may make life a bit easier but it being GitHub Pages/Jekyll rather than Rails may make some bits a bit harder.

**Comment by knpwrs** [comment]
I just noticed that this repo has JSON for every formula 😅. That actually makes things _significantly_ easier. It's dead simple to consume those files and send them up to Algolia.

The brewgolia demo is hosted on Netlify because they provide a static site platform that makes it easy to build frontend code before deploying the final site. In my experience Github pages is limited to a fixed selection of jekyll plugins, is that still the case? With Netlify we're able to build a React app with webpack and deploy the result. I also have experience deploying [react-static](https://github.com/nozzle/react-static) sites on Netlify which could potentially be a good fit for what's being done here (it's super easy to make data-driven routes that are all compiled out to static HTML files (no JavaScript required) -- the data can also come from anywhere, not just files available on the filesystem). I'm currently working on another website which deploys to Netlify and sends an index up to Algolia (referenced [here](https://github.com/knpwrs/brew-dump/issues/3#issuecomment-385475707)).

For my own reference, should the Homebrew team want to move forward with Algolia, would they be open to a platform other than Github pages? Everything is obviously possible on Github pages, but having to commit frontend build artifacts is less than ideal imho (which, as far as I'm aware, would be required with Github pages short of doing everything in vanilla JS with no minification). Netlify is also incredibly simple to use as it can automatically deploy from Github repos and takes little to no configuration. As you can see from the brewgolia demo, they also support Let's Encrypt for HTTPS (recently added to Github pages as well).

**Comment by MikeMcQuaid** [comment]
> I just noticed that this repo has JSON for every formula 😅.

There's also a single, huge JSON file that contains JSON for every file.

> In my experience Github pages is limited to a fixed selection of jekyll plugins, is that still the case?

Yes.

> For my own reference, should the Homebrew team want to move forward with Algolia, would they be open to a platform other than Github pages?

No, sorry. I'd also rather avoid using e.g. React in favour of raw JS if at all possible.

**Comment by knpwrs** [comment]
> I'd also rather avoid using e.g. React in favour of raw JS if at all possible.

It's possible. It's just not very fun, though that really depends on what browsers you want to support.

**Comment by MikeMcQuaid** [comment]
If it's a pain to integrate Algolia without ditching GitHub Pages and using a JavaScript framework (for a single search box) I think it's probably the wrong solution for this problem. A cursory glance shows that there's stuff like https://github.com/bvaughn/js-search which seems like a simpler solution. I'm going to change the issue accordingly to not be specific to a given solution and we'll welcome PRs taking any approach.

**Comment by knpwrs** [comment]
I put together a _quick_ vanilla JS example on CodeSandbox using a fuzzy search library I'm already familiar with, [Fuse.js](https://github.com/krisk/fuse) (10.1 KB minified, 3.6 KB gzipped, overall comparable with `js-search`). The demo also puts some metrics on the page -- how much data was downloaded, how long it took to index, and how long it took to search. The demo code itself is < 50 LOC including metrics.

Demo available here: https://8zv40jxzl.codesandbox.io/
Source available here: https://codesandbox.io/s/8zv40jxzl

If you have a strong preference towards doing things client side, my only real hesitation is that the entire JSON object is 6MB. I'm on gigabit internet, so it doesn't really affect me (loads in < 500ms). On Chrome's "fast 3G" preset it takes about 7-8 seconds to download and startup. On a 15Mbps connection it takes a little more than a second to start up.

**Comment by MikeMcQuaid** [comment]
> If you have a strong preference towards doing things client side

I'm open to doing things server side I'm just not sure I understand (yet) why the API is more complex than "here's a new JSON index" and later asking "what results do I get from this search queries on this index"?

**Comment by knpwrs** [comment]
I see. I may have blended a few independent suggestions together in the interest of brevity. Allow me to break apart my suggestions.

# Suggestion 1: Update the Algolia Index with a CI Server

Since the Homebrew registry is based on git, it feels very natural to me to update the Algolia index using a CI job. We have designed a method to update the index, including removing old formulae, based on git commit SHAs, that I believe is very robust. It appears that this repository is updated by Travis already, so updating the Algolia index should be fairly straightforward by tapping into that job.

# Suggestion 2: Use a Frontend Build System

If the first suggestion passes merit, then it only feels natural to me to build the frontend with CI.

## Suggestion 2a: Build the Search Page in CI

There is nothing intrinsically difficult about using Algolia in vanilla JavaScript vs using something like Fuse. Neither route necessitates using a build system. That said, using a built library such as React solves some potentially tricky problems for free. It is smart about ordering dom reads and writes properly and I would argue that even for small applications using a framework that focuses on functional purity and immediate-mode rendering will always lead to a more maintainable codebase than performing manual DOM manipulation. ***It will also help to guard against injection attacks without you needing to think about it***. The way the Fuse demo is currently constructed somebody could theoretically submit a malicious package to the registry which would inject script tags into the search page -- you can guard against this on your own, but why not use something that's already thought of that and has stood the test of time? In the future you will also automatically gain functionality provided by the framework, e.g., the upcoming work Facebook has been doing with async rendering in React.

## Suggestion 2b: Build the Individual Formulae Pages in CI

If building the search page feels like a natural extension of using CI to build the Algolia index, then I believe it doesn't hurt to evaluate if anything could be made simpler or more robust in building the individual formulae pages. [`react-static`](https://github.com/nozzle/react-static) is a very nice static site generator with data-driven routing. You would still get individual HTML pages, so everything (except search) would work without JavaScript enabled on the client. If all the formulae pages and the search page are all built in `react-static` then the entire site becomes a seamless experience with no page reloads for navigation while still maintaining individual static HTML pages.

# Suggestion 3: Netlify

There is no technical reason that frontend builds cannot be deployed by committing to the git repo. Suggestions `2a` and `2b` are therefore independent of this suggestion. Netlify is nice because it's an all-in-one CI and static site hosting platform. That said, nothing necessitates Netlify, I just find committing build artifacts to be less than optimal. However, if you are comfortable with committing build artifacts and are persuaded by my reasoning to build the frontend rather than write it with script tags, there is no technical reason that blocks a deployment to Github pages.

# In Closing

Suggestions `1`, `2a`, `2b`, and `3` are all independent of each other. If you want to only go with the first suggestion and scrap everything else, that's fine because nothing about Algolia makes vanilla JavaScript necessarily difficult. It can be used via script tags or raw API calls. All of that said, I think there can be major wins by using a built frontend rather than a vanilla JS frontend. Suggestions `2a` and `2b` are not decrees either. React could easily be replaced with [Vue](https://vuejs.org/) and `react-static` could easily be replaced with [`Vuepress`](https://github.com/vuejs/vuepress), for instance.

If you'd like a demo of all of my suggestions working together, I'm more than happy to expand my Brewgolia demo to use `react-static`. Otherwise, I'm happy moving forward with whatever solution you feel is most appropriate.

**Comment by MikeMcQuaid** [comment]
> And because you are already using Jekyll maybe it will even be possible to just use the jekyll-algolia plugin to do the reindexing at each push.

Yeh, this sounds perfect.

> Now that we're talking about integrating for real on your website, let's see what stack would be preferable for you.

👍 

> The one thing that is still missing is a way to rank the packages according to one another. Algolia can do textual relevance, but we can also rank elements based on some custom metrics. In this case I think that ideally we would want to take into account the popularity of packages through the analytics data. I'm unsure how to do that at the moment as it seem to live in another repo.

I would hold off on this for now; I'm not sure when we'll be able to integrate this data.

**Comment by TrevorSayre** [comment]
@pixelastic Unfortunately GitHub pages restricts you to only a small set of plugins: https://help.github.com/articles/configuring-jekyll-plugins/#optional-plugins

So your suggestion will not work, from what I can tell. Can you confirm this @MikeMcQuaid since you're a senior engineer at GitHub?

**Comment by knpwrs** [comment]
I was just about to post what @TrevorSayre was saying, with the additional caveat that we would need to commit the search admin API secret inside the repository in order for it to run in Github pages / Jekyll. It seems to be that building the index on CI is still the way to go? Travis allows secrets to be encrypted in the repo or provided as environment variables.

**Comment by pixelastic** [comment]
Sorry if I wasn't clear, but what I suggested was to host the Jekyll website on GitHub pages (as opposed to moving to Netlify) but having Travis handling the Algolia re-indexing in parallel. I've documented how to do that here: https://community.algolia.com/jekyll-algolia/github-pages.html

So yeah, basically what @knpwrs was suggesting as well I think: by using Travis we don't have to make the API key public because we can put it in Travis' ENV variables.

**Comment by MikeMcQuaid** [comment]
> So yeah, basically what @knpwrs was suggesting as well I think: by using Travis we don't have to make the API key public because we can put it in Travis' ENV variables.

Yep, this sounds good 👍

**Comment by knpwrs** [comment]
@pixelastic quick question on my part -- would your plugin index the pages as they are output or would it index the individual fields of the formulae? If the former, it seems like we could construct a more precise search and interface by simply feeding the JSON directly to Algolia, bypassing Jekyll.

**Comment by pixelastic** [comment]
@knpwrs The jekyll-algolia plugin will index the content of the generated HTML page, but also any items set in the Jekyll collections. So if the JSON files are considered collection items (I didn't check), the plugin should be able to index them easily.

That being said, as the data is already in JSON format, just pushing them to Algolia without the plugin might be even quicker. I was mentioning the plugin in case @MikeMcQuaid wanted to use it in the Jekyll website itself, and in that case we could have killed to birds with one stone.

**Comment by koraktor** [comment]
@pixelastic The formulae are not a Jekyll collection, but data items.

A collection would be nicer IMHO, but Jekyll doesn’t support rendering multiple output formats (e.g. HTML and JSON) from one collection. That’s why there’s a dummy page for each formula in `/formula` and `/api/formula`.

**Comment by pixelastic** [comment]
Thanks for the information. While it might still be possible to do the whole indexing through the Jekyll plugin, in the current context I think it might actually require more work than a quick js script to read the JSOn and push it as @knpwrs suggested initially.

**Comment by MikeMcQuaid** [comment]
Yeh, we only will need to index the data items 👍

**Comment by michaelblyons** [comment]
Is this expected to be fixed by #96? 

Context: I used to have a [custom search engine](chrome://settings/searchEngines) in my browser for braumeister.org, and I was a little disappointed when it stopped working. I've been lurking this thread basically ever since. The interim replacement, a GitHub code search matching `<search-string> user:Homebrew language:Ruby path:Formula`, has not been nearly as nice. (I also use `brew search`, but sometimes I just want to use a web browser.)

**Comment by MikeMcQuaid** [comment]
> Is this expected to be fixed by #96?

@michaelblyons That or something similar in the next month or so I think.

**Comment by MikeMcQuaid** [comment]
This has 🚢d. Great work @SMillerDev!
