### ISSUE TITLE
Search does not find openjdk with "jdk"

### ISSUE THREAD

**Issue by lathspell** [Homebrew/formulae.brew.sh#514]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ x] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

## What you were trying to do (and why)

Search for "jdk" shows "openjdk@11"

## What happened (include screenshots)

It only shows "oracle jdk" and some others

## What you expected to happen

It also shows "openjdk" (which it does if one enters the full string "openjdk")

**Comment by SMillerDev** [comment]
Sounds like https://github.com/Homebrew/formulae.brew.sh/issues/442, pinging @shortcuts.

**Comment by shortcuts** [comment]
Hey!

Unfortunately, unless the Homebrew team decides to boost the results for `openjdk` ([page_rank](https://docsearch.algolia.com/docs/config-file/#using-page-rank)), the weight of the results is computed on the engine side.

It seems that increasing the number of results doesn't show the `openjdk` anyway ([sandbox](https://codesandbox.io/s/brewall-8c4io?file=/src/index.js)), so I'll try to see if there's any indexing issue just in case!

**Comment by EricFromCanada** [comment]
It looks like the indexer only notices "JDK" within words if it's capitalized differently. For example, using the sandbox link above, a search for "jdk" lists the [adoptopenjdk](https://formulae.brew.sh/cask/adoptopenjdk) and [microsoft-openjdk](https://formulae.brew.sh/cask/microsoft-openjdk) casks because they have all-caps "JDK" in their description, while each [openjdk](https://formulae.brew.sh/formula/openjdk) formula, having the description "Development kit for the Java programming language", does not.
