### ISSUE TITLE
RSS Feed is "missing"

### ISSUE THREAD

**Issue by atheken** [Homebrew/formulae.brew.sh#931]
- [x] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

## What you were trying to do (and why)

I used to be able to get updates from an RSS/Atom feed for the site.

## What happened (include screenshots)

That feed looks like it's gone.

## What you expected to happen

See updates from the site in an RSS feed. This was useful in discovering new apps in my feed reader.

I would be willing to update the Jekyll config to generate a feed again, if this is something that the team is open to.

**Comment by SMillerDev** [comment]
https://github.com/Homebrew/formulae.brew.sh/pull/858 seems to remove it

**Comment by EricFromCanada** [comment]
It was removed because the feed didn't contain any useful information. The [jekyll-feed plugin](https://github.com/jekyll/jekyll-feed) automatically adds posts to the feed (as is done for the Homebrew Blog at https://brew.sh/atom.xml), but new formula/cask additions aren't posts, they're just items in [data files](https://jekyllrb.com/docs/datafiles/). I'm not aware of a way to funnel those into an RSS feed since Jekyll doesn't keep track of when each was added, but you're welcome to try!
It's not RSS, but [this query](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+is%3Amerged+in%3Atitle+%28new+formula%29+) will return formulae that have been recently added to `homebrew/core`.
